[workspace]
resolver = "2"
members = ["a_hello_world", "b_string_interpolation", "c_var_types", "d_shadowing", "e_data_types", "f_functions", "g_pass_by_value_n_reference", "h_struct", "i_enum", "j_enum_2", "k_generic", "l_traits_interfaces", "m_trait_debug", "n_iterators"]
